name: Build ESP32 Scream Receiver

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [esp32s3]
        include:
          - target: esp32s3
            name: "ESP32-S3 (USB)"
            config_define: IS_USB

    name: Build ${{ matrix.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
        
      - name: Configure project
        run: |
          # Modify the config.h file to enable appropriate target
          # First disable both targets
          sed -i 's/^#define IS_SPDIF/\/\/#define IS_SPDIF/' main/config.h
          sed -i 's/^#define IS_USB/\/\/#define IS_USB/' main/config.h
          # Then enable the correct target
          sed -i 's/^\/\/#define '${{ matrix.config_define }}'/#define '${{ matrix.config_define }}'/' main/config.h
          
          # Copy the default configuration
          if [ -f sdkconfig.${{matrix.target}} ]; then
            cp sdkconfig.${{matrix.target}} sdkconfig
          fi

      - name: Install ESP-IDF
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: 'v5.4'
          target: ${{ matrix.target }}
          
      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ matrix.target }}
          path: |
            build/esp32-scream-receiver.bin
            build/*.bin
            build/*.elf
            build/bootloader/bootloader.bin
            build/partition_table/partition-table.bin
          retention-days: 7
          
  create-release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        
      - name: Create release zip files
        run: |
          zip -r esp32-firmware.zip firmware-esp32/
          zip -r esp32-s3-firmware.zip firmware-esp32s3/
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            esp32-firmware.zip
            esp32-s3-firmware.zip
          draft: false
          prerelease: false
